const HM={
  key:{lang:'hm_lang',vehicles:'hm_vehicles',bookings:'hm_bookings',maintenance:'hm_maintenance'},
  get(k,f=[]){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},
  set(k,v){localStorage.setItem(k,JSON.stringify(v))},
  uid(prefix){return `${prefix}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`},
  money(n){return new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(n||0))},
  initDemo(){
    if(!localStorage.getItem(this.key.vehicles)) this.set(this.key.vehicles,[
      {id:'HM-EV-DEMO-001',plate:'DEMO-001',brand:'MG',model:'Maxus 9',year:'2026',energy:'EV',seats:6,odometer:18500,status:'Available',battery:96,revenue:12400,trips:4,hours:18.5,nextServiceKm:22000,insuranceExpiry:'2027-03-31',registrationExpiry:'2027-03-31',notes:'Demo record — replace with actual fleet data.'},
      {id:'HM-EV-DEMO-002',plate:'DEMO-002',brand:'MG',model:'Maxus 9',year:'2026',energy:'EV',seats:6,odometer:23100,status:'Booked',battery:94,revenue:18100,trips:6,hours:27,nextServiceKm:25000,insuranceExpiry:'2027-02-28',registrationExpiry:'2027-02-28',notes:'Demo record — replace with actual fleet data.'}
    ]);
    if(!localStorage.getItem(this.key.bookings)) this.set(this.key.bookings,[]);
    if(!localStorage.getItem(this.key.maintenance)) this.set(this.key.maintenance,[{id:'MT-DEMO-001',vehicleId:'HM-EV-DEMO-002',type:'Periodic Service',dueDate:'2026-08-20',dueKm:25000,status:'Due Soon',cost:0,notes:'Demo maintenance reminder.'}]);
  }
};
HM.initDemo();

const translations={
th:{navServices:'บริการ',navEnterprise:'Enterprise',navFleet:'รถในระบบ',bookNow:'จองเลย',eyebrow:'WHITE-LABEL ADVANCE BOOKING PLATFORM',heroTitle:'ระบบจองรถพร้อมคนขับ สำหรับผู้ประกอบการรถของคุณเอง',heroLead:'บริหารการจอง รถ คนขับ การใช้งาน รายได้ และการบำรุงรักษาในระบบเดียว พร้อมใช้แบรนด์ของผู้ประกอบการเอง',tryBooking:'ทดลองจองรถ',openDashboard:'เปิด Dashboard',servicesKicker:'BOOKING PRODUCTS',servicesTitle:'หนึ่งแพลตฟอร์ม หลายรูปแบบบริการขนส่ง',hourly:'รถพร้อมคนขับรายชั่วโมง',hourlyDesc:'แพ็กเกจ 3 / 5 / 8 ชั่วโมง หรือเต็มวัน กำหนดจำนวนจุด แวะรอ และค่าชั่วโมงเกินได้',airport:'รับส่งสนามบิน',airportDesc:'ตั้งราคาคงที่หรือกำหนดเอง พร้อมข้อมูลเที่ยวบินและรายละเอียดการรับลูกค้า',corporate:'Corporate Mobility',corporateDesc:'จองในนามบริษัท ขอใบกำกับภาษี ดูการใช้งานรายเดือน และเก็บข้อมูลการเดินทางเพื่อ ESG',enterpriseTitle:'แบรนด์ของคุณ รถของคุณ ลูกค้าของคุณ',enterpriseDesc:'HERO Move Enterprise เป็นระบบเบื้องหลังสำหรับธุรกิจรถพร้อมคนขับหรือรถเช่าพร้อมคนขับ โดยไม่เปิดรับรถภายนอกเข้ามาปะปนกับ Fleet ของผู้ประกอบการ',featureBooking:'Booking & Dispatch',featureFleet:'ลงทะเบียนรถและวัดการใช้งาน',featureDriver:'จัดคนขับและตารางว่าง',featureMaintenance:'บำรุงรักษาและวันหมดอายุเอกสาร',featureFinance:'รายได้และประสิทธิภาพรถ',featureCorporate:'Corporate / ESG records',fleetKicker:'FLEET INTELLIGENCE',fleetTitle:'รถทุกคันมี Operational Profile ถาวร',fleetDesc:'เก็บข้อมูลรถ การใช้งาน รายได้ ระยะทาง สถานะ ประกัน ภาษี สุขภาพแบตเตอรี่ EV และประวัติการซ่อมบำรุง',manageFleet:'ทดลอง Fleet Management',esgTitle:'ข้อมูลการเดินทางพร้อมต่อยอดสู่ Green Mobility และ ESG',esgDesc:'บันทึกประเภทพลังงาน ระยะทาง และข้อมูลความยั่งยืนของผู้ประกอบการ การคำนวณคาร์บอนอย่างเป็นทางการจะเพิ่มภายหลังเมื่อกำหนดวิธีคำนวณและแหล่งข้อมูลที่ตรวจสอบได้',ctaTitle:'ทดลอง MVP ที่ใช้งานได้แล้ว',ctaDesc:'สร้าง Booking ลงทะเบียนรถ เพิ่มรายการบำรุงรักษา และดู Dashboard ได้ทันที ข้อมูลทดลองเก็บใน Browser นี้จนกว่าจะเชื่อม Backend Production',newBooking:'สร้าง Booking',registerVehicle:'ลงทะเบียนรถ'},
en:{navServices:'Services',navEnterprise:'Enterprise',navFleet:'Fleet',bookNow:'Book Now',eyebrow:'WHITE-LABEL ADVANCE BOOKING PLATFORM',heroTitle:'Advance chauffeur booking software for operators with their own fleet.',heroLead:'Manage bookings, vehicles, drivers, utilization, revenue and maintenance in one system — under the operator’s own brand.',tryBooking:'Try Booking',openDashboard:'Open Dashboard',servicesKicker:'BOOKING PRODUCTS',servicesTitle:'One platform. Multiple transport products.',hourly:'Hourly Chauffeur',hourlyDesc:'3 / 5 / 8 hour or full-day packages with configurable stops, waiting time and overtime.',airport:'Airport Transfer',airportDesc:'Fixed or configurable airport transfer products with flight details and meet-and-greet notes.',corporate:'Corporate Mobility',corporateDesc:'Company bookings, tax invoice requests, monthly usage and ESG-ready trip records.',enterpriseTitle:'Your brand. Your fleet. Your customers.',enterpriseDesc:'HERO Move Enterprise operates as the booking and fleet engine behind a chauffeur or car-rental-with-driver business. No outside partner vehicles are mixed into the operator’s fleet.',featureBooking:'Booking & dispatch',featureFleet:'Vehicle registration & utilization',featureDriver:'Driver assignment & availability',featureMaintenance:'Maintenance & document expiry',featureFinance:'Revenue & performance',featureCorporate:'Corporate / ESG records',fleetKicker:'FLEET INTELLIGENCE',fleetTitle:'Every vehicle has a permanent operational profile.',fleetDesc:'Track vehicle identity, usage, revenue, mileage, availability, insurance, registration, EV battery health and maintenance history.',manageFleet:'Manage Fleet Demo',esgTitle:'Corporate mobility records ready for greener transport reporting.',esgDesc:'Record vehicle energy type, EV usage, trip distance and operator-defined sustainability information. Formal carbon accounting can be added after verified methodology and data sources are agreed.',ctaTitle:'Try the working MVP now.',ctaDesc:'Create bookings, register vehicles, add maintenance records and view the operator dashboard. Data is stored in this browser for the demo until the production backend is connected.',newBooking:'New Booking',registerVehicle:'Register Vehicle'},
zh:{navServices:'服务',navEnterprise:'企业版',navFleet:'车队',bookNow:'立即预订',eyebrow:'白标预约出行平台',heroTitle:'为自有车队运营商打造的司机用车预约系统',heroLead:'在同一个系统中管理订单、车辆、司机、使用率、收入与维护，并可使用运营商自己的品牌。',tryBooking:'体验预订',openDashboard:'打开仪表板',servicesKicker:'预订产品',servicesTitle:'一个平台，多种出行产品。',hourly:'按小时司机服务',hourlyDesc:'3 / 5 / 8 小时或全天套餐，可配置停靠点、等候时间及超时费用。',airport:'机场接送',airportDesc:'支持固定或自定义机场接送价格，并记录航班与接待说明。',corporate:'企业出行',corporateDesc:'企业预订、税务发票申请、月度使用记录及ESG出行数据。',enterpriseTitle:'您的品牌、您的车队、您的客户。',enterpriseDesc:'HERO Move Enterprise 为司机服务及带司机租车公司提供白标预订与车队管理系统，不混入外部合作车辆。',featureBooking:'预订与调度',featureFleet:'车辆登记与利用率',featureDriver:'司机分配与可用时间',featureMaintenance:'维护与证件到期',featureFinance:'收入与绩效',featureCorporate:'企业 / ESG记录',fleetKicker:'车队智能',fleetTitle:'每辆车都有永久运营档案。',fleetDesc:'记录车辆身份、使用、收入、里程、可用状态、保险、登记、EV电池健康及维护历史。',manageFleet:'体验车队管理',esgTitle:'为绿色出行与ESG报告准备企业出行数据。',esgDesc:'记录能源类型、EV使用、行程距离及运营商定义的可持续信息。正式碳核算将在确认可验证的方法和数据源后加入。',ctaTitle:'立即体验可用MVP。',ctaDesc:'现在即可创建订单、登记车辆、添加维护记录并查看运营仪表板。正式后端连接前，演示数据保存在当前浏览器。',newBooking:'新建订单',registerVehicle:'登记车辆'}
};
function applyLang(lang){document.documentElement.lang=lang;localStorage.setItem(HM.key.lang,lang);document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang]?.[k]) el.textContent=translations[lang][k]});const sel=document.getElementById('language');if(sel)sel.value=lang}
document.addEventListener('DOMContentLoaded',()=>{const lang=localStorage.getItem(HM.key.lang)||'th';applyLang(lang);const sel=document.getElementById('language');if(sel)sel.addEventListener('change',e=>applyLang(e.target.value));const vs=HM.get(HM.key.vehicles),bs=HM.get(HM.key.bookings),ms=HM.get(HM.key.maintenance);const a=document.getElementById('homeVehicleCount'),b=document.getElementById('homeBookingCount'),c=document.getElementById('homeMaintenanceCount');if(a)a.textContent=vs.length;if(b)b.textContent=bs.length;if(c)c.textContent=ms.filter(x=>x.status!=='Completed').length});